services:
  responsive-cv-frontend:
    build: .
    # networks:
    #   frontend:
    #     aliases:
    #       - cv-frontend
    ports:
      - 8080:8080

# networks:
#   frontend:
#     driver: bridge