services:
  responsive-cv-frontend:
    build: .
    networks:
      cv-network:
        aliases:
          - frontend
    ports:
      - 80:80

networks:
  cv-network:
    name: cv-network